# Generated by Django 5.0.14 on 2026-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Logesh M', max_length=100)),
                ('heading', models.CharField(default='I AM AVAILABLE FOR FULL STACK DEVELOPMENT', max_length=200)),
                ('bio', models.TextField(default="Hi, I'm Logesh M. A passionate Full Stack Developer dedicated to creating visually appealing, accessible, and high-performance web applications.")),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('projects_completed', models.IntegerField(default=20)),
                ('years_experience', models.IntegerField(default=1)),
                ('passion_percentage', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'About Information',
                'verbose_name_plural': 'About Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(help_text="e.g., '2023 - 2025'", max_length=50)),
                ('title', models.CharField(help_text="e.g., 'M.Sc Computer Science'", max_length=200)),
                ('institution', models.CharField(help_text="e.g., 'Periyar University'", max_length=200)),
                ('grade', models.CharField(help_text="e.g., '6.5 CGPA'", max_length=50)),
                ('grade_label', models.CharField(default='Graduation Index', max_length=100)),
                ('progress_offset', models.FloatField(default=35.19, help_text='Radial bar offset SVG dashoffset (e.g. 35.19 for 6.5 CGPA out of 10)')),
            ],
            options={
                'verbose_name_plural': 'Education Timeline',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tags', models.CharField(help_text="Comma-separated tags, e.g. 'React, Django, PostgreSQL'", max_length=500)),
                ('features', models.CharField(blank=True, help_text='Comma-separated feature summary', max_length=500, null=True)),
                ('techs_used', models.CharField(blank=True, help_text='Comma-separated backend/frontend techs used', max_length=500, null=True)),
                ('status', models.CharField(default='Completed', help_text="e.g. 'Completed' or 'In Progress'", max_length=50)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Core', 'Core'), ('Outer', 'Outer Circle (Wheel)'), ('Inner', 'Inner Circle (Wheel)'), ('General', 'General')], default='General', max_length=50)),
                ('level', models.IntegerField(default=80, help_text='Skill level percentage (0-100)')),
                ('icon_class', models.CharField(help_text="FontAwesome class, e.g., 'fab fa-react'", max_length=100)),
                ('icon_color', models.CharField(blank=True, help_text="Hex color or styling, e.g. '#61dafb'", max_length=50, null=True)),
                ('angle', models.FloatField(default=0.0, help_text='Angle in degrees for orbit wheel')),
                ('radius', models.FloatField(default=155.0, help_text='Radius in pixels for orbit wheel')),
                ('description', models.CharField(blank=True, help_text='Short description of skill usage', max_length=255, null=True)),
            ],
        ),
    ]
