# Generated by Django 6.0 on 2026-07-07 10:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[api.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[api.models.validate_image_file]),
        ),
    ]
