services:
  - type: web
    name: devworldofml
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_DEBUG
        value: "False"